name: Build & Publish

on:
  push:
    branches:
      - main # This runs the action when code is pushed to the 'main' branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies (npm or yarn based on your setup)
      - name: Install dependencies
        run: npm install

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: npm run test:unit

      # Step 5: Run Integration Tests
      - name: Run Integration Tests
        run: npm run test:integration

      # Step 6: Run Component Tests
      - name: Run Component Tests
        run: npm run test:component

      # Step 7: Run Contract Tests
      - name: Run Contract Tests
        run: npm run test:contract

      # Step 8: Build the Vue app
      - name: Build app
        run: npm run build

      # Step 9: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 10: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 11: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tasker-ui:${{ github.sha }} .

      # Step 12: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tasker-ui:${{ github.sha }}

      # Optionally, add latest tag
      - name: Tag Docker image as latest
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/tasker-ui:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/tasker-ui:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tasker-ui:latest
