name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (uat or prod)'
        required: true
        default: 'uat'

jobs:
  deploy-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # Authenticate with GCP by creating a temporary file from the secret
      - name: Set up Google Cloud Authentication
        run:
          echo "${{ secrets.GCP_SA_KEY }}" > ${{ runner.temp }}/gcp-key.json

          # Authenticate with GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      # Ensure gcloud is authenticated with the service account
      - name: Activate Service Account
        run: gcloud auth activate-service-account --key-file=${{ runner.temp }}/gcp-key.json

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Deploy UI to GCP
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "uat" ]]; then
            gcloud run deploy tasker-ui-uat --image docker.io/naumanz/tasker-ui:uat --region us-central1 --allow-unauthenticated
          elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            gcloud run deploy tasker-ui-prod --image docker.io/naumanz/tasker-ui:prod --region us-central1 --allow-unauthenticated
          fi
