name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (uat or prod)'
        required: true
        default: 'uat'
        type: choice
        options:
          - uat
          - prod
jobs:
  deploy-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Write GCP service account key to file
        run: |
          printf "${{ secrets.GCP_SA_TOKEN }}" | base64 -d  > /home/runner/work/_temp/gcp-key.json

      # Authenticate with GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Ensure gcloud is authenticated with the service account
      - name: Activate Service Account
        run: gcloud auth activate-service-account --key-file=/home/runner/work/_temp/gcp-key.json

      - name: Determine Environment Variables
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
              echo "ENVIRONMENT=prod" >> $GITHUB_ENV
              echo "BASE_API_URL=${{ secrets.BASE_API_URL_PROD }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment  }}" == "uat" ]]; then
              echo "ENVIRONMENT=uat" >> $GITHUB_ENV
              echo "BASE_API_URL=${{ secrets.BASE_API_URL_UAT }}" >> $GITHUB_ENV
          else
              echo "Unknown environment. Exiting."
              exit 1
          fi
      - name: Deploy frontend to ${{ env.ENVIRONMENT}}
        run: |
          gcloud run deploy tasker-ui-${{ env.ENVIRONMENT }} \
          --image docker.io/naumanz/tasker-ui:${{ env.ENVIRONMENT }} \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars VITE_BASE_API_URL=${{ env.BASE_API_URL }}
