name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (uat or prod)'
        required: true
        default: 'uat'

jobs:
  deploy-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t naumanz/tasker-ui:${{ github.event.inputs.environment }} .
          docker push naumanz/tasker-ui:${{ github.event.inputs.environment }}

      - name: Configure GCP SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy UI to GCP
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "uat" ]]; then
            gcloud run deploy tasker-ui-uat --image docker.io/naumanz/tasker-ui:uat --region us-central1 --allow-unauthenticated
          elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            gcloud run deploy tasker-ui-prod --image docker.io/naumanz/tasker-ui:prod --region us-central1 --allow-unauthenticated
          fi
