name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main # This runs the action when code is pushed to the 'main' branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tasker-ui:${{ github.sha }} .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tasker-ui:${{ github.sha }}

      # Optionally, add latest tag
      - name: Tag Docker image as latest
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/tasker-ui:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/tasker-ui:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tasker-ui:latest
